FROM python:3.5

RUN apt-get update

WORKDIR /app

RUN pip install cython
RUN pip install addok
RUN pip install addok-fr
RUN pip install addok-france
RUN pip install addok-csv
RUN pip install gunicorn

COPY local.py /app

ENV ADDOK_CONFIG_MODULE /app/local.py
ENV REDIS_HOST redis

EXPOSE 7878

CMD gunicorn addok.http.wsgi -b 0.0.0.0:7878
