FROM python:3.5

RUN apt-get update
RUN apt-get -qy install git wget

WORKDIR /app

RUN pip install cython
RUN pip install git+https://github.com/addok/addok
RUN pip install git+https://github.com/addok/addok-fr
RUN pip install git+https://github.com/addok/addok-france
RUN pip install git+https://github.com/addok/addok-trigrams

RUN wget http://bano.openstreetmap.fr/data/bano-57.json.gz
RUN gunzip bano-57.json.gz

COPY local.py /app

ENV ADDOK_CONFIG_MODULE /app/local.py
ENV REDIS_HOST redis

CMD addok batch bano-57.json
