FROM python:3.5

RUN apt-get update
RUN apt-get -qy install git

WORKDIR /app

RUN pip install cython
RUN pip install git+https://github.com/addok/addok
RUN pip install git+https://github.com/addok/addok-fr
RUN pip install git+https://github.com/addok/addok-france
RUN pip install git+https://github.com/addok/addok-trigrams
RUN pip install git+https://github.com/addok/addok-csv
RUN pip install gunicorn

COPY local.py /app

ENV ADDOK_CONFIG_MODULE /app/local.py
ENV REDIS_HOST redis

EXPOSE 7878

CMD gunicorn addok.http -b 0.0.0.0:7878
