version: "3"

services:
  addock-db:
    image: redis
    volumes:
      - ./redis-data:/data
  addock-api:
    build:
      context: .
    links:
      - addock-db:redis
    ports:
      - 7878:7878
    volumes:
      - ./addok-data:/data
